server:
  port: 8080
spring:
  application:
#  应用的名称
    name: reggie_take_out
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: zhx15570182336
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
#    数据库层面命名带下划线 而java命名是驼峰命名 这样建立映射关系实现自动封装
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
#    主键的生成策略
      id-type: ASSIGN_ID

reggie:
  path: D:\reggie\imgs\